version: '2'
services:
    nginx:
        image: nginx:latest
        container_name: nginx
        ports:
            - "8000:8000"
        volumes:
            - ./src:/src
            - ./config/nginx:/etc/nginx/conf.d
        depends_on:
            - webapp
    
    webapp:
        build: .
        container_name: web
        command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0"
        depends_on:
            - mysqldb
        volumes:
            - ./src:/src
        expose:
            - "8000"
            
    mysqldb:
        image: mysql
        container_name: mysql
        environment:
            MYSQL_ROOT_PASSWORD: password